# Data Story Gender Pay Gap

## Salary and Age

Salaries tend to rise when people get older. Let's see what the basic correlation between these two features is.

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df1422 = pd.read_parquet('../data/SO_2014_2022.pq', engine='pyarrow')

df1422.head(n=10)

,Year,Salary,JobSat,YearsCode,YearsCodePro,Age,Education,OrgSize,LastNewJob,Employment,RespondentType,JobSeek,Gender,Student,Country,CodingActivities,DevType,LearnCodeFrom,LangPresent
0,2022,69318.0,<NA>,10,5.0,25-34,master,500 to 999 employees,None,fulltime,dev,None,male,no,Germany,School or academic work,Data scientist or machine learning specialist;...,"Books / Physical media;School (i.e., Universit...",C;C++;Java;JavaScript;MATLAB;Python;Scala;SQL;...
1,2022,NaN,<NA>,9,<NA>,18-24,master,NaN,None,fulltime,dev,None,male,no,Sweden,Hobby;Contribute to open-source projects;Schoo...,"Engineer, data;Developer, full-stack;Developer...","School (i.e., University, College, etc)",C++;Java;JavaScript;Python;R;SQL
2,2022,NaN,<NA>,25,20.0,45-54,tertiary,NaN,None,independent,dev,None,male,no,Indonesia,Hobby;Contribute to open-source projects,"Developer, front-end;Developer, full-stack;Dev...",Books / Physical media;Other online resources ...,Bash/Shell/PowerShell;Dart;HTML/CSS;JavaScript...
3,2022,NaN,<NA>,6,<NA>,18-24,bachelor,NaN,None,notwork,dev,None,male,no,Russia,Hobby;School or academic work,"Student;Developer, mobile",Books / Physical media;Friend or family member...,Bash/Shell/PowerShell;C;C++;Go;Groovy;Haskell;...
4,2022,NaN,<NA>,4,<NA>,25-34,master,NaN,None,fulltime,dev,None,female,no,Iran,Contribute to open-source projects,Data scientist or machine learning specialist;...,Books / Physical media,C++
5,2022,NaN,<NA>,3,<NA>,18-24,secondary,NaN,None,parttime,stu,None,male,no,Hungary,School or academic work,"Developer, front-end;Student","School (i.e., University, College, etc)",C#;Dart;HTML/CSS;Java;Kotlin;SQL
6,2022,27652.0,<NA>,18,10.0,25-34,bachelor,"1,000 to 4,999 employees",None,fulltime,dev,None,male,no,Colombia,Hobby,"Developer, full-stack;Developer, back-end",Books / Physical media;Other online resources ...,Bash/Shell/PowerShell;Elixir;HTML/CSS;JavaScri...
7,2022,NaN,<NA>,4,<NA>,18-24,NaN,NaN,None,notwork,stu,None,male,yes,Germany,None,None,Friend or family member;Other online resources...,Bash/Shell/PowerShell;C;C#;C++;Go;HTML/CSS;Jav...
8,2022,NaN,<NA>,9,6.0,25-34,bachelor,2 to 9 employees,None,independent,dev,None,male,no,Brazil,Hobby;Bootstrapping a business;Freelance/contr...,"Developer, full-stack;Developer, mobile","Other online resources (e.g., videos, blogs, f...",C;C++;Java;Kotlin;Python
9,2022,15431.0,<NA>,5,5.0,25-34,bachelor,20 to 99 employees,None,fulltime,dev,None,male,no,Ghana,Freelance/contract work,"Developer, back-end",On the job training;Coding Bootcamp,JavaScript;Ruby

In [1]:
# Plot the data
# g1 = px.scatter(df1422,
#                    x="Age",
#                    y="Salary",
#                    height=700)
# g1.show()